version: 0.2

env:
  variables:
    ECR_REPO: "brain-task-app"
    IMAGE_TAG: "latest"
    ACCOUNT_ID: "952499956741"
    AWS_REGION: "ap-south-1"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - docker login --username rajasekaran191 --password dckr_pat_CIpp_1uVyDBdVPJcNVt9kt9dUU8
      - echo Building and Pushing Docker image...
      - docker build -t $ECR_REPO:$IMAGE_TAG .
      - docker tag $ECR_REPO:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
  post_build:
    commands:
      - echo "Forcing credential refresh..."
      # This line is the magic - it forces the AWS CLI to get a fresh token for EKS
      - aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME
      
      - echo "Deploying with validation disabled..."
      # We add --validate=false and --kubeconfig to be 100% sure
      - kubectl apply -f k8s/deployment.yaml -f k8s/service.yaml --validate=false
      
      - echo "Updating image..."
      - kubectl set image deployment/brain-tasks-deployment brain-tasks=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
      - echo "Deployment Complete!"
artifacts:
  files:
    - 'k8s/deployment.yaml'
    - 'k8s/service.yaml'
